### PR TITLE
Add camera intrinsics of DTR

### PR DESCRIPTION
**Pull request by peci1**
CC @tpet .

### CODE REVIEW

**Comment by peci1** [comment]
Resolves #909

**Comment by peci1** [comment]
This will need a Fuel update, too.

**Review by nkoenig — APPROVED** [review]

**Comment by nkoenig** [comment]
The Fuel models have been updated.

**Comment by peci1** [comment]
@nkoenig I don't see the updates on Fuel. Last changed 21 May, 3 days before this issue has been posted.

**Comment by peci1** [comment]
https://app.ignitionrobotics.org/OpenRobotics/fuel/models/csiro_data61_dtr_sensor_config_1 and https://app.ignitionrobotics.org/OpenRobotics/fuel/models/csiro_data61_dtr_sensor_config_2

**Comment by acschang** [comment]
> @nkoenig I don't see the updates on Fuel. Last changed 21 May, 3 days before this issue has been posted.

Just checked as well, I don't see the updated intrinsics either.

**Comment by nkoenig** [comment]
Thanks for point this out. The models have been updated.

**Comment by peci1** [comment]
Thanks, I verified the intrinsics are there now.

**Pull request merged**
