### PR TITLE
New config with thermal camera: CERBERUS_M100_SENSOR_CONFIG_2

### PR DESCRIPTION
**Pull request by iche033**
Created a new config: `CERBERUS_M100_SENSOR_CONFIG_2`: 

This is a copy of `CERBERUS_M100_SENSOR_CONFIG_1` with thermal camera sensor added to `model.sdf` and `vehicle_topics.launch` updated to bridge the thermal camera topics

Still need clarification on (**Edit: done**):
* ~~exact FLIR Tau2 model used (there are a few product variations on the [FLIR Tau2 page](https://www.flir.com/products/tau-2/))~~
    * Modeled after [this configuration](https://www.flir.com/products/tau-2/?model=46640007H)
* ~~location of the sensor on the drone~~
    * Adjusted camera and thermal camera pose

cc @tiralonghipol @mihirk284 

The thermal camera is mounted side by side with the rgb camera:

cerberus_m100_config_2_thermal

to test:

```
ign launch cave_circuit.ign worldName:=simple_cave_01 circuit:=cave robotName1:=Xa robotConfig1:=CERBERUS_M100_SENSOR_CONFIG_2
```

Signed-off-by: Ian Chen <ichen@osrfoundation.org>

### CODE REVIEW

**Comment by mihirk284** [comment]
Hi @iche033 ,
I've made minor modifications to the position of the RGB camera sensor to also accommodate the Thermal camera model.
The updated sdf looks like this (only the pose has been changed) :-
```xml
<visual name="camera_visual">
    <pose>0.192 -0.015 -0.023 0 0.174533 0</pose>
    ... same as before ...
</visual>
<sensor name="camera_front" type="camera">
    <pose>0.192 -0.015 -0.023 0 0.174533 0</pose>
    ....same as before
</sensor>

<!-- thermal camera -->
<visual name="thermal_camera_visual">
    <pose>0.192 0.015 -0.023 0 0.174533 0</pose>
    ... same as before ...
</visual>
<sensor name="thermal_camera" type="thermal">
  <pose>0.192 0.015 -0.023 0 0.174533 0</pose>
  ... same as before
</sensor>
```

**Comment by iche033** [comment]
great, thanks for the pose changes. I'll take care of it

**Review by adlarkin — COMMENTED** [review]
The thermal camera is working for me, but I noticed a line in the camera output in rViz that I did not see when testing other robots with thermal cameras: 
thermal_camera_line

**Comment by iche033** [comment]
> The thermal camera is working for me, but I noticed a line in the camera output in rViz that I did not see when testing other robots with thermal cameras:

is that the grid in rviz?

**Comment by adlarkin** [comment]
> is that the grid in rviz?

Yes, it was, so this actually looks good to me!

**Review by adlarkin — APPROVED** [review]

**Comment by mihirk284** [comment]
Hi @iche033 and @adlarkin,
I don't know if I should open this as an issue or just ask here on the same thread if there's something different in what I was doing for simulating the robot with the thermal camera.

I noticed that there's a significant difference between the image above, and what I was seeing on my machine.

When I tried to simulate the image, it looked a bit different on my machine.
image (4)

Also, the floor of the cave looked a little different to me, with some additional flickering:-

https://user-images.githubusercontent.com/27280479/106822638-50829600-6634-11eb-98ef-fafd81cd9bef.mp4

Thanks,
Mihir

**Comment by adlarkin** [comment]
> I noticed that there's a significant difference between the image above, and what I was seeing on my machine.

Are you using the Ignition binaries, or are you building Ignition from source? We are still in the process of making `ign-gazebo` and `ign-rendering` releases that will add the thermal camera functionality. Also, it actually turns out that the image I originally posted is incorrect - there was a bug that was just recently addressed in https://github.com/ignitionrobotics/ign-rendering/pull/230.

**Comment by adlarkin** [comment]
@mihirk284 you should see something like this once inside the tunnel if you're building `ign-gazebo` and `ign-rendering` from source: 
correct_view_in_tunnel

**Comment by mihirk284** [comment]
Thank you @adlarkin,
I think I had not updated the ign dome repos for a while
I'll pull the repos from source and try it out :)

**Comment by adlarkin** [comment]
> Thank you @adlarkin,
> I think I had not updated the ign dome repos for a while
> I'll pull the updated repos and try it out :)

Sounds good! You'll need to build `ign-gazebo` and `ign-rendering` from source, but should be able to use the binaries for all the other ignition libraries.

**Comment by nkoenig** [comment]
The Fuel models have been updated to use:
```
      <sensor name="thermal_camera" type="thermal">
        <pose>0.435 -.01 0.125 0 0 0</pose>
        <camera name="thermal_camera">
          <horizontal_fov>0.4922</horizontal_fov>
          <lens>
            <intrinsics>
              <!-- fx = fy = width / ( 2 * tan (hfov / 2 ) ) -->
              <fx>764.35630</fx>
              <fy>764.35630</fy>
              <!-- cx = ( width + 1 ) / 2 -->
              <cx>192.5</cx>
              <!-- cy = ( height + 1 ) / 2 -->
              <cy>144.5</cy>
              <s>0</s>
            </intrinsics>
          </lens>
          <image>
            <width>384</width>
            <height>288</height>
            <format>L8</format>
          </image>
          <clip>
            <near>0.1</near>
            <far>100</far>
          </clip>
        </camera>
        <always_on>1</always_on>
        <update_rate>25</update_rate>
        <plugin
          filename="ignition-gazebo-thermal-sensor-system"
          name="ignition::gazebo::systems::ThermalSensor">
          <min_temp>233.15</min_temp>
          <max_temp>833.15</max_temp>
        </plugin>
      </sensor>
```

**Comment by peci1** [comment]
The thermocam got lost from Fuel... #821.

**Pull request merged**
