### PR TITLE
log detach events, and new performer detector header information

### PR DESCRIPTION
**Pull request by nkoenig**
To test:

1. Run simulation: `ign launch cave_circuit.ign worldName:=simple_cave_01 robotName1:=X1 robotConfig1:=X1_SENSOR_CONFIG_1 robotName2:=X2 robotConfig2:=X3_SENSOR_CONFIG_1 marsupial1:=X1:X2`

2. Tail the `events` yaml file: `tail -f /tmp/ign/logs/events.yml`

3. Detach the X2: `rostopic pub /X2/detach std_msgs/Empty "{}"`

4. Teleop the robots through the cave entrance to see the extra header information. You'll need version 2 of https://app.ignitionrobotics.org/OpenRobotics/fuel/models/Cave%20Starting%20Area%20Type%20B

Signed-off-by: Nate Koenig <nate@openrobotics.org>

### CODE REVIEW

**Comment by iche033** [comment]
The event system worked and I saw the detach and start events logged in the yml file.
 
I did however notice that the `enter` and `exit` events were triggered outside the detection box:

enter_event

**Comment by nkoenig** [comment]
> The event system worked and I saw the detach and start events logged in the yml file.
> 
> I did however notice that the `enter` and `exit` events were triggered outside the detection box:
> 
> enter_event

What version of the starting area do you have?

**Comment by nkoenig** [comment]
> > The event system worked and I saw the detach and start events logged in the yml file.
> > I did however notice that the `enter` and `exit` events were triggered outside the detection box:
> > enter_event
> 
> What version of the starting area do you have?

And you also have ign-gazebo 2.21 installed, correct?

**Comment by iche033** [comment]
> What version of the starting area do you have?

I just pulled the latest changes from ign-gazebo2 and it's working for me now. Sorry for the noise!

**Comment by iche033** [comment]
There are some conflicts, otherwise the changes look good to me

**Comment by iche033** [comment]
merge with `master` and resolved conflicts in 429fc6c

**Pull request merged**
