### PR TITLE
Model submission for Absolem sensor configurations 6,7,8 by CTU-CRAS-Norlab

### PR DESCRIPTION
**Pull request by peci1**
Depends and builds on top of #859 (sensor configs 3,4,5), #877 and #878. That is why you see so much commits. If you want to see just changes from the sensor configurations, look e.g. at https://github.com/ctu-vras/subt/compare/submitted_models/ctu_cras_norlab_absolem_improved...ctu-vras:submitted_models/ctu_cras_norlab_absolem/clone .

Everything that was written in #859 applies also here. The main difference of these sensor configs is that they do not have the Ladybug omnicamera, and instead they use our custom omnicamera solution based on 5 pcs of Basler ACE 2 Pro cameras. This is beneficial for occlusions by body parts, which are inevitable when using a centralized omnicam, but are nicely avoided by putting each camera on the edge of the robot body.

The field of view of the Basler cameras is experimentally measured. We took a ruler, shot a picture of it, and by using a bit of trigonometry, we ended up with horizontal FOV of 86.5°. For the trigonometrical computation we used the datasheet value of "Front focal length", which is 9.95 mm. We sketched a triangle from the point on lens axis that is 9.95 mm inside the lens (measured from the vertex of the outern-most lens). One side of the triangle we used for computation is distance of the ruler from the point inside lens, and the other side is the distance viewed on the ruler.

The theoretical value for a 4 mm lens on 1/2.3" chip is 79°, so I assume the difference to our measured value is done by distortion, which is not modeled in the simulator, and neither is it modeled in the theoretical equation.

The computation I used for horizontal FOV is:

    degrees(2*atan(tan(0.0066)/(2*0.004))) = 79.04 

Where `0.004` is effective focal length and `0.0066` is the sensor width (both from datasheet). This theoretical value is valid for focusing into infinity. Closer focus can decrease the FOV by a few degrees.

### CODE REVIEW

**Comment by peci1** [comment]
I force-pushed a SDF 1.6 version of Absolem SC6-8 based on #877 and #878. The geometry and behavior is exactly the same as in the original version.

**Comment by peci1** [comment]
I rebased on top of #859 to resolve conflicts brought in by #551.

**Review by acschang — CHANGES_REQUESTED** [review]
The initial assessment of these additional sensor configurations for the Absolem model is complete, however there are some issues to resolve before these additional sensor configurations can be merged and utilized in a competitive setting:

- [x] Please add lens intrinsic values to the Omnicam cameras.
- [x] Please add all missing components to the RViz visualization.
- [x] Please include all updates from Absolem PR for sensor configurations 3, 4, and 5 (#859).
- [x] Please regenerate the `model.sdf` for sensor configurations 6, 7, and 8 with the updates from #859.

Please address the issues noted above and add commits to this pull request as soon as possible. The submission is expected to be incorporated into the SubT Virtual Testbed pending a successful review.

**Comment by peci1** [comment]
All of the issues from last review have been resolved.

**Review by acschang — APPROVED** [review]

**Review by nkoenig — APPROVED** [review]

**Pull request merged**
