### PR TITLE
New config with thermal camera: MARBLE_HUSKY_SENSOR_CONFIG_3 and MARBLE_HUSKY_SENSOR_CONFIG_4

### PR DESCRIPTION
**Pull request by adlarkin**
The thermal camera used for this model is the same as the one in #773. The only difference between the thermal camera for this model and the one in #773 should be the the camera's location.

`sensor config 3 = sensor config 1 + thermal camera`, and `sensor config 4 = sensor config 2 + thermal camera`

Here is where I have placed the thermal camera (right above the lower LIDAR sensor): 
husky_thermal_camera

Signed-off-by: Ashton Larkin <ashton@openrobotics.org>

### CODE REVIEW

**Comment by adlarkin** [comment]
@iche033 I believe we should add this code snippet to the fuel model's `model.sdf` files in order to have the thermal camera placement as pictured above:

```xml
      <!-- thermal camera -->
      <visual name="thermal_camera_visual">
        <pose >0.485 0 0.169 0 0 0</pose>
        <geometry>
          <box>
            <size>0.02 0.025 0.025</size>
          </box>
        </geometry>
      </visual>
      <sensor name="thermal_camera" type="thermal">
        <pose >0.485 0 0.169 0 0 0</pose>
        <camera name="thermal_camera">
          <horizontal_fov>0.4922</horizontal_fov>
          <lens>
            <intrinsics>
              <!-- fx = fy = width / ( 2 * tan (hfov / 2 ) ) -->
              <fx>764.35630</fx>
              <fy>764.35630</fy>
              <!-- cx = ( width + 1 ) / 2 -->
              <cx>192.5</cx>
              <!-- cy = ( height + 1 ) / 2 -->
              <cy>144.5</cy>
              <s>0</s>
            </intrinsics>
          </lens>
          <image>
            <width>384</width>
            <height>288</height>
          </image>
          <clip>
            <near>0.1</near>
            <far>100</far>
          </clip>
        </camera>
        <always_on>1</always_on>
        <update_rate>25</update_rate>
      </sensor>
```

**Comment by adlarkin** [comment]
@iche033 I just tested configurations 3 and 4. Everything seems to be working for me! I can echo data from the topics, and I can visualize the thermal camera in rviz.

**Review by iche033 — APPROVED** [review]
works for me as well

**Comment by nkoenig** [comment]
Here is the latest output image stream from the thermal camera:

thermal

**Comment by nkoenig** [comment]
The Fuel models have been updated to use:
```
      <sensor name="thermal_camera" type="thermal">
        <pose>0.435 -.01 0.125 0 0 0</pose>
        <camera name="thermal_camera">
          <horizontal_fov>0.4922</horizontal_fov>
          <lens>
            <intrinsics>
              <!-- fx = fy = width / ( 2 * tan (hfov / 2 ) ) -->
              <fx>764.35630</fx>
              <fy>764.35630</fy>
              <!-- cx = ( width + 1 ) / 2 -->
              <cx>192.5</cx>
              <!-- cy = ( height + 1 ) / 2 -->
              <cy>144.5</cy>
              <s>0</s>
            </intrinsics>
          </lens>
          <image>
            <width>384</width>
            <height>288</height>
            <format>L8</format>
          </image>
          <clip>
            <near>0.1</near>
            <far>100</far>
          </clip>
        </camera>
        <always_on>1</always_on>
        <update_rate>25</update_rate>
        <plugin
          filename="ignition-gazebo-thermal-sensor-system"
          name="ignition::gazebo::systems::ThermalSensor">
          <min_temp>253.15</min_temp>
          <max_temp>673.15</max_temp>
        </plugin>
      </sensor>
```

**Comment by peci1** [comment]
The thermocam got lost from Fuel... #821.

**Pull request merged**
