### PR TITLE
 Model submission for Husky sensor configurations 1,2 by CTU-CRAS-Norlab

### PR DESCRIPTION
**Pull request by peci1**
This is our sensor configuration of Husky robot. It is the same base platform as already existing `MARBLE_HUSKY` robot.

- The robotic platform is a standard Clearpath Husky
- The sensor rack sitting on top of the Husky includes:
  - A Robosense RS-LiDAR-16 (or the new equivalent Leishen C16, depending on how many we break)
  - An omnivision setup of 6 Basler Ace2 (a2A1920-51gcPRO) cameras with C125-0418-5M-P Basler Lens
  - LED spotlights pointing in the same direction as the cameras
  - Xsens MTi-100 IMU
  - Rear-facing Intel Realsense D435i
- The model includes the default SubT gas sensor
- Weight: Approx. 61kg
  - Husky: 50kg
  - Sensor rack: 11 kg
- Sensor config 2 carries 12 comms breadcrumbs in addition to the above.

### CODE REVIEW

**Comment by peci1** [comment]
Some screenshots maybe useful during acceptance testing:

2021-03-29T04:19:54 395564411
default_gzclient_camera(1)-2021-03-29T04_26_21 098699
default_gzclient_camera(1)-2021-03-29T04_26_39 943506

**Comment by peci1** [comment]
I downgraded model.sdf to SDF version 1.6 as requested for all our models. This model used no 1.7 features, so just changing the `<sdf version>` attribute was enough. I checked that with `ign sdf --force-version 8.9.1 -k`.

**Comment by peci1** [comment]
I did the same changes that were requested in #842.

**Review by acschang — APPROVED** [review]
The initial assessment of the model is complete and no changes are currently warranted. This submission will continue to be evaluated in the next stage of our review process.

**Review by nkoenig — APPROVED** [review]

**Pull request merged**
