### PR TITLE
Model Submission for Add Pam UAV sensor configuration 1

### PR DESCRIPTION
**Pull request by knoedler**
This is a quadrotor based on our Pam UAV.

### CODE REVIEW

**Comment by nkoenig** [comment]
Bounding box `[0.764 0.724 0.286645]`

**Review by acschang — CHANGES_REQUESTED** [review]
The initial assessment of the Coordinated Robotics Pam model is complete however there are some issues to resolve before this model can be merged and utilized in a competitive setting:

- Please verify whether the point LIDAR sensors mounted to the top and bottom of the vehicle are part of the physical robot's configuration. If so, please add them to the `Sensors` section of the `specifications.md` file.
- Please resolve all noted issues in the `vehicle_topics.launch` file.
- Please provide validation data for your model.  The validation data is necessary to complete the evaluation. If not provided, the model's maximum velocity will be limited to 4m/s and battery life set to 10min. When the model validation data can be provided later, please submit a PR updating the model.

Please address the issues noted above in this pull request. Once the above issues are fixed, your submission will move onto the next review stage!

**Comment by knoedler** [comment]
Point Lidar model added to specifications.md
vehicle_topics.launch updated
Validation data is still linked in the specifications.md

**Comment by acschang** [comment]
Validation data LGTM.  My apologies for missing it earlier.

The only currently outstanding task for this model is resolving the `RobotModel` visualization in RViz.

**Comment by knoedler** [comment]
> The only currently outstanding task for this model is resolving the `RobotModel` visualization in RViz.

Since the rviz visualization was optional, I blanked out the file and disabled the launching in description.launch to resolve the problems with the urdf.

**Review by acschang — APPROVED** [review]

**Comment by acschang** [comment]
Continued in #854

**Pull request closed without merging**
