### PR TITLE
Combine all circuit launch files

### PR DESCRIPTION
**Pull request by adlarkin**
I have combined the following circuit launch files into a single file named `competition.ign`:
* [cave_circuit.ign](https://github.com/osrf/subt/blob/662cfffe7a1bee3be4c4b14700640a5179f419a1/subt_ign/launch/cave_circuit.ign)
* [tunnel_circuit_practice.ign](https://github.com/osrf/subt/blob/a9c45f1e5f15da76e261937fe7be17bb000427ed/subt_ign/launch/tunnel_circuit_practice.ign)
* [urban_circuit.ign](https://github.com/osrf/subt/blob/b73ab3fcdca5881504b8645ec73cdc5491c5d05b/subt_ign/launch/urban_circuit.ign)
* [competition.ign](https://github.com/osrf/subt/blob/a9c45f1e5f15da76e261937fe7be17bb000427ed/subt_ign/launch/competition.ign)

This new change has introduced a new parameter, `circuit`, that must be defined when running `ign launch`. `circuit` must be either `cave`, `tunnel`, or `urban`. Here are some example commands:

1. run a cave circuit world:
```
ign launch competition.ign circuit:=cave worldName:=simple_cave_01 robotName1:=X2_3 robotConfig1:=X2_SENSOR_CONFIG_3
```
2. run a tunnel circuit world:
```
ign launch competition.ign circuit:=tunnel worldName:=tunnel_circuit_practice_01 robotName1:=X1 robotConfig1:=X1_SENSOR_CONFIG_1
```
3. run an urban circuit world:
```
ign launch competition.ign circuit:=urban worldName:=urban_qual robotName1:=HUSKY robotConfig1:=COSTAR_HUSKY_SENSOR_CONFIG_1
```

---
**TODO** update wiki/READMEs anywhere that are affected by this change?

Signed-off-by: Ashton Larkin <ashton@openrobotics.org>

### CODE REVIEW

**Review by nkoenig — APPROVED** [review]

**Comment by nkoenig** [comment]
The wiki has been updated.

**Comment by peci1** [comment]
What about adding some autodetection based on world name? I.e. `if "cave" in worldName: circuit = "cave"` (that's Python syntax, as I don't know Ruby). It'd work for most of the provided worlds, and for those where not (i.e. custom worlds), the user would have to supply it.

**Comment by zwn** [comment]
> What about adding some autodetection based on world name?

That is what we do in our scripts. I honestly don't even understand why there is such a distinction.

**Comment by peci1** [comment]
It sets parameters of the comms model and staging area spawn positions:

https://github.com/osrf/subt/blob/8f5187b7eede8de5baf2596f5cda5807a1b80cab/subt_ign/launch/competition.ign#L70-L92

**Comment by zwn** [comment]
But that is the property of the world, right? So why is it set from the outside? The same goes for the spawn positions.

**Pull request merged**
