### PR TITLE
Model Submission for CSIRO DATA61 Spot Sensor Config 1

### PR DESCRIPTION
**Pull request by TJMolnar**

### CODE REVIEW

**Comment by TJMolnar** [comment]
@nkoenig Is there some outstanding work required from us to get this merged in?

**Comment by acschang** [comment]
@TJMolnar I made a few updates on https://github.com/osrf/subt/tree/submitted_models/csiro_data61_spot_sensor_config_1 however I noticed the scripts to generate the revised `model.sdf` using the nested Spot configuration did not pan out as anticipated.  Were you modifying the `model.sdf` urdf directly or regenerating it through the script?  I checked the validation data videos/uploads for the DTR and OzBot but did not see inclusion of the current battery voltage or battery voltage depletion rate.  Do you have this data?

**Comment by TJMolnar** [comment]
> @TJMolnar I made a few updates on https://github.com/osrf/subt/tree/submitted_models/csiro_data61_spot_sensor_config_1 however I noticed the scripts to generate the revised `model.sdf` using the nested Spot configuration did not pan out as anticipated. Were you modifying the `model.sdf` urdf directly or regenerating it through the script? I checked the validation data videos/uploads for the DTR and OzBot but did not see inclusion of the current battery voltage or battery voltage depletion rate. Do you have this data?

@nkoenig I believe the model.sdf was modified directly for use in ignition (the xacro files were only intended for generation of an ros+gazebo compatible urdf/sdf for visualisation). The voltage data from the battery is actually logged by our motor controllers and is under the /ethercat_drive_states topic (apologies for the obfuscated rostopic location but it is a quirk of the setup of our tracked platforms)

**Comment by acschang** [comment]
Thanks. Continued in #1035

**Pull request closed without merging**
