### PR TITLE
Thermal Camera Consistency

### PR DESCRIPTION
**Pull request by acschang**
Updated the thermal cameras on MARV, Mike, and Karen to meet the standards established in #773, #776, #777, and #779.

**MARV:**
marv_thermal

**Mike:**
mike_thermal

**Karen:**
karen_thermal

### CODE REVIEW

**Comment by peci1** [comment]
Please, do not decrease near clip distance on MARV. The value that is there is not arbitrary - it is a result of extensive testing. As mentioned in some of our models earlier, Gazebo has some rendering issues when the robot changes orientation. Not only yaw, but also pitch/roll play a role. If the near clip distance is too low, the thermocamera image gets blinded by the camera mesh in some situations.

**Comment by peci1** [comment]
It seems there is inconsistency in the camera center computation (along the lines pointed in https://github.com/osrf/subt/issues/406 ). Some robots got -1 here and some got +1. Can you please definitively decide what is the correct formula?

**Comment by acschang** [comment]
> Please, do not decrease near clip distance on MARV. The value that is there is not arbitrary - it is a result of extensive testing. As mentioned in some of our models earlier, Gazebo has some rendering issues when the robot changes orientation. Not only yaw, but also pitch/roll play a role. If the near clip distance is too low, the thermocamera image gets blinded by the camera mesh in some situations.

Noted.  The clip distance is not expected to be adjusted with this PR.

> It seems there is inconsistency in the camera center computation (along the lines pointed in #406 ). Some robots got -1 here and some got +1. Can you please definitively decide what is the correct formula?

The standard is +1 as noted in the following:
```
<!-- fx = fy = width / ( 2 * tan (hfov / 2 ) ) -->
<!-- cx = ( width + 1 ) / 2 -->
<!-- cy = ( height + 1 ) / 2 -->
```

I'll look into resolving the issue pointed out in #406.

**Comment by mjcarroll** [comment]
I believe this was still waiting on @acschang resolve the issues from #406.  There are still a few cameras in here with inconsistent updates to the principle points.  I can make the changes if need be.

**Comment by acschang** [comment]
> > Please, do not decrease near clip distance on MARV. The value that is there is not arbitrary - it is a result of extensive testing. As mentioned in some of our models earlier, Gazebo has some rendering issues when the robot changes orientation. Not only yaw, but also pitch/roll play a role. If the near clip distance is too low, the thermocamera image gets blinded by the camera mesh in some situations.
> 
> Noted. The clip distance is not expected to be adjusted with this PR.
> 
> > It seems there is inconsistency in the camera center computation (along the lines pointed in #406 ). Some robots got -1 here and some got +1. Can you please definitively decide what is the correct formula?
> 
> The standard is +1 as noted in the following:
> 
> ```
> 
> 
> 
> ```
> 
> I'll look into resolving the issue pointed out in #406.

It appears that the #406 is correct and the values for cx/cy are off by 1 pixel for a number of models but they will not adjusted for finals as the inconsistency for the principle point can be derived from `camera_info` and correcting the issue will change behavior that has been present since the transition to Ignition.

However, I did adjust the thermal camera principle point for MARV to align with the principle point in other camera sensors for this vehicle model.

**Comment by acschang** [comment]
> I believe this was still waiting on @acschang resolve the issues from #406. There are still a few cameras in here with inconsistent updates to the principle points. I can make the changes if need be.

This PR is good to go.  We are not going to adjust camera cx/cy values in other models before finals.

**Comment by peci1** [comment]
Should this be retargeted to final_event branch?

**Review by mjcarroll — APPROVED** [review]

**Pull request merged**
