### PR TITLE
Added joy teleop support for flipper control (using deadman + D-pad).

### PR DESCRIPTION
**Pull request by peci1**

### CODE REVIEW

**Comment by acschang** [comment]
These new features will not be incorporated into the SubT Virtual Testbed prior to Cave Circuit. We will keep this PR open for consideration after Cave Circuit.

**Comment by peci1** [comment]
I know, that's okay ;)

**Comment by peci1** [comment]
I updated this branch with master. To test this feature, launch `roslaunch subt_example teleop.launch` and either connect a logitech gamepad and play around with the D-pad and deadman buttons, or simulate the gamepad by these commands:

Lift up:
```
rostopic pub /joy sensor_msgs/Joy "header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
axes: [0, 0, 0, 0, 1, 1]
buttons: [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0]" 
```

Put down:
```
rostopic pub /joy sensor_msgs/Joy "header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
axes: [0, 0, 0, 0, -1, -1]
buttons: [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0]" 
```

**Comment by peci1** [comment]
Another merge with master (no conflict).

**Comment by peci1** [comment]
Friendly ping. I'm preparing another flipper-equipped robot model and this would come handy.

**Comment by nkoenig** [comment]
This works for me. Is the following snippet suitable to add to [this wiki page](https://github.com/osrf/subt/wiki/Example-Setup)?

* If you are using a robot with flippers, such as the [CTU CRAS NORLAB Absolem Sensor Config 1](https://subtchallenge.world/OpenRobotics/fuel/models/CTU_CRAS_NORLAB_ABSOLEM_SENSOR_CONFIG_1), then you can use the D-pad to control the flippers.
        - ↑: raises the front flippers
        - ↓: lowers the front flippers
        - ←: raises the rear flippers
        - →: lowers the rear flippers.

**Comment by peci1** [comment]
The snippet looks good (if the directions are okay, which I never remember :) ).

You can also remove the flashlight part of the snippet, which is IMO obsolete.

**Review by nkoenig — APPROVED** [review]

**Pull request merged**
