### PR TITLE
fix direction of lights on robot robotika/Freyja

### PR DESCRIPTION
**Pull request by m3d**
The lights unfortunately pointed to the ground - fixed now.
thanks
   Martin/Robotika Team

### CODE REVIEW

**Comment by nkoenig** [comment]
Lighting before:
freyja_before

Lighting after:
freyja_after


Looks good. This will make it into the code freeze.

**Comment by m3d** [comment]
thanks a lot :)
m.

**Comment by m3d** [comment]
Is there a way how to check that this was really deployed on CloudSim? We would like to fix also configuration 2 (after "unfreeze") and they both look the same??

**Comment by nkoenig** [comment]
Those lighting issues are due to the javascript library used to render the scene. A fix has been applied [here](https://gitlab.com/ignitionrobotics/web/gz3d/-/merge_requests/33) and needs to be rolled out to the portal. The docker images do not require changes.

**Comment by m3d** [comment]
@nkoenig great - thanks for info

**Pull request merged**
