### PR TITLE
Model submission for the CSIRO Data61 DTR platform sensor configurations 1 and 2 by CSIRO

### PR DESCRIPTION
**Pull request by TJMolnar**
- Submission of the DTR platform
- Minor fixes to the existing OZBOT ATR platform (added correct visual elements)

### CODE REVIEW

**Comment by acschang** [comment]
The initial assessment of the CSIRO Data61 DTR model is complete however there are some issues to resolve before this model can be merged and utilized in a competitive setting:

- Please add the [wheel slip plugin](https://github.com/osrf/subt/pull/569); if you need assistance with this we can add it as part of the later review process.
- Please resolve all instances of floating sensors and sensor mounts by affixing to the robot.
- Please check the `specifications.md` file for typos. 

Please address the issues noted above and update this pull request. Once the above issues are resolved, your submission will be accepted!

**Comment by nkoenig** [comment]
Here is an example [wheel slip plugin](https://github.com/osrf/subt/blob/master/submitted_models/x1_sensor_config_6/launch/spawner.rb#L61).

**Comment by nkoenig** [comment]
@TJMolnar , can you take a look at the comments posted by @acschang  in this PR and make the necessary changes? Let me know if you have questions or need assistance.

**Comment by nkoenig** [comment]
The bounding box for this model is
```
Min[-0.403097 -0.2453 -0.104585] Max[0.406835 0.2453 0.485]
```

**Comment by TJMolnar** [comment]
@nkoenig @acschang Thank you for the feedback, apologies on the delay. I have added the wheel slip plugin but I'm not confident on the tuning, help on this would be much appreciated. In regards to the floating lights, they are positioned in the correct location for how they are mounted on the robot, the simplified mesh file for the body is missing the mounting bracket for them. I can add this back in if it is required.

**Comment by acschang** [comment]
> @nkoenig @acschang Thank you for the feedback, apologies on the delay. I have added the wheel slip plugin but I'm not confident on the tuning, help on this would be much appreciated. In regards to the floating lights, they are positioned in the correct location for how they are mounted on the robot, the simplified mesh file for the body is missing the mounting bracket for them. I can add this back in if it is required.

Please re-add the simple mounting bracket to affix the lights to the vehicle frame.  Also, please add the wheel slip parameter to the `spawner.rb` file for sensor configuration 2.

**Comment by acschang** [comment]
@TJMolnar do you have any updates regarding the changes requested above?

**Comment by TJMolnar** [comment]
@acschang Yes, currently just waiting on an updated drawing for the vehicle body from our mechanical team. Should be finalised soon

**Review by acschang — APPROVED** [review]
The submitted changes resolve the outstanding issues.

**Comment by nkoenig** [comment]
[X] Optical frames
[X] Pan mechanism rotates appropriately
[X] Wheel slip looks good
[X] Sensor check via Rviz
[ ] Breadcrumbs for config 2 don't appear in the correct location, I'll make a separate PR for this.

**Pull request merged**
