### PR TITLE
Model Submission for CTU-CRAS-NORLAB MARV

### PR DESCRIPTION
**Pull request by acschang**
Continuation of #832

### CODE REVIEW

**Comment by peci1** [comment]
@acschang  Thanks for the changes. I'll take another round of updates to our PRs in about an hour.

**Review by nkoenig — APPROVED** [review]
Looks good.

**Comment by peci1** [comment]
@acschang It seems the description on Fuel is wrong. I see:

> 5 HD wide cameras
> 2 HD cameras 

But the robot has 2 fisheyes and 5 86° cameras. So should the description be the other way round?

**Comment by angelacmaio** [comment]
> @acschang It seems the description on Fuel is wrong. I see:
> 
> > 5 HD wide cameras
> > 2 HD cameras
> 
> But the robot has 2 fisheyes and 5 86° cameras. So should the description be the other way round?

[This has been resolved on the SubT Tech Repo](https://subtchallenge.world/OpenRobotics/fuel/models/ctu_cras_norlab_marv_sensor_config_1).

**Pull request merged**
