### PR TITLE
Model submission for m100 sensor configuration 1 from CERBERUS.

### PR DESCRIPTION
**Pull request by nkoenig**
modified pull request target branch
default → model_pr_432

### CODE REVIEW

**Comment by acschang** [comment]
The initial assessment of the CERBERUS M100 model is complete, however there are some issues to resolve before this model can be merged and utilized in a competitive setting:

- Rotors visually appear to spin more slowly than intended. Please resolve.
- Please add a gas sensor to this model for consistency with other robot models in the SubT Tech Repo, even if the real UAV does not include a gas sensor.
- The camera resolution and intrinsic parameters do not seem to match the FLIR Blackfly S datasheet. Please match the parameters.
- The simulated LIDAR has a higher vertical resolution than indicated by the Velodyne datasheet. Please match the parameters.

Please address the issues noted above and then submit a pull request to update your submission by **5 JUNE**. The submissions are expected to be incorporated into the SubT Virtual Testbed pending a successful review.

**Comment by tiralonghipol** [comment]
should be ok now
waiting for feedback

**Comment by tiralonghipol** [comment]
latest commit should have fixed these points

**Comment by acschang** [comment]
> latest commit should have fixed these points

Can you please link submit a new PR into `model_pr_432` with the changes?

**Comment by tiralonghipol** [comment]
> > latest commit should have fixed these points
> 
> Can you please link submit a new PR into `model_pr_432` with the changes?

should be done

**Comment by mjcarroll** [comment]
@tiralonghipol Is this file: submitted_models/cerberus_m100_sensor_config_1/meshes/m100.dae.orig still being used or can it be removed?

**Comment by tiralonghipol** [comment]
@mjcarroll  it can be removed

**Comment by nkoenig** [comment]
I'm merging this PR into the cave_feature_release3 branch. This robot will be available when the feature release branch is merged into master.

**Pull request merged**
