### PR TITLE
Dome plugin update for CERBERUS ANYmal B

### PR DESCRIPTION
**Pull request by Samu24**
PR adds updated binaries for CERBERUS ANYmal B.

Note: The PR could not be tested yet on our end due to #728

### CODE REVIEW

**Review by adlarkin — COMMENTED** [review]
When testing this, I saw the following output:

```
Error while loading the library [/ws/install/lib/libAnymalBControlPlugin1.so]: libignition-gazebo2.so.2: cannot open shared object file: No such file or directory
[Err] [SystemLoader.cc:75] Failed to load system plugin [libAnymalBControlPlugin1.so] : couldn't load library on path [/ws/install/lib/libAnymalBControlPlugin1.so].
```

It looks like you're still depending on the blueprint version of ignition gazebo. Can you fix this, and double check for any other dependencies that need to be updated?

**Comment by Samu24** [comment]
Thanks for the review @adlarkin. I will check.

**Comment by Samu24** [comment]
@adlarkin I updated the branch with `master`. With this commit I can run the simulation without issues. 

Here the steps I did to run the simulation:

- Checkout branch `submitted_models/cerberus_anymal_b_dome_plugin_update`
- source `/opt/ros/melodic/setup.zsh`
- `catkin_make install`
- `source install/setup.zsh`
- `ign launch -v 4 competition.ign robotName1:=anymal_b robotConfig1:=CERBERUS_ANYMAL_B_SENSOR_CONFIG_1`

The model spawns and is controllable. I do not get any errors for plugin loading.

Can you please try again and let me know if the issue persists.

Thanks

P.S. `ignition-dome` version is `1.0.0-2`

**Review by adlarkin — APPROVED** [review]
Things are working for me now, thanks!

**Pull request merged**
