### PR TITLE
Model submission for Kolibri sensor configuration 1 by Cerberus.

### PR DESCRIPTION
**Pull request by olov-andersson**
Submission of the new Kolibri robot.

### CODE REVIEW

**Comment by acschang** [comment]
I made some modifications to the submission on https://github.com/osrf/subt/tree/submitted_models/cerberus_kolibri_sensor_config_1 however the battery plugin does not seem to even load alongside their custom controller as it treats the quadrotor as a simple rigid body with no pitch/roll allowed thus bypassing the MRS plugin.  @nkoenig do you have any suggestions?

**Comment by acschang** [comment]
Continued in #1037

**Comment by olov-andersson** [comment]
Hi @acschang, I noticed this PR was closed, but the PR #1037 you linked refers to another drone. Is anything expected of us here? As you noted we did not use the quadrotor plugin because it does not fly as a quadrotor (i.e. tilt to move). It is a multi-directional actuated tri-copter with a 3rd party closed-source control system, which unfortunately made it a very difficult fit with the SubT simulator packages.

**Comment by acschang** [comment]
> Hi @acschang, I noticed this PR was closed, but the PR #1037 you linked refers to another drone. Is anything expected of us here? As you noted we did not use the quadrotor plugin because it does not fly as a quadrotor (i.e. tilt to move). It is a multi-directional actuated tri-copter with a 3rd party closed-source control system, which unfortunately made it a very difficult fit with the SubT simulator packages.

Good catch on the PR link.  Continued in #1043.  Nothing further is expected of you at this time.  We understand your limited knowledge of the controller and are actively looking for an avenue for this platform to adhere to SubT Virtual Testbed standards while maintaining its advertised motion characteristics.

**Pull request closed without merging**
