### PR TITLE
Model Submission for R2 configuration 1 from Explorer

### PR DESCRIPTION
**Pull request by HongbiaoZ**

### CODE REVIEW

**Comment by acschang** [comment]
Thank you for robot model submission however we are unable to evaluate your submission until your submission meets the criteria laid out in the [Simulation Model Preparation Guide](https://www.subtchallenge.com/resources/Simulation_Model_Preparation_Guide.pdf).  Please add a `specifications.md` file to your submission with details laid out in the aforementioned guide.

**Comment by HongbiaoZ** [comment]
Thank you. A specifications.md has been added to the model package.

**Comment by nkoenig** [comment]
It looks like there is disagreement between the wheel collisions and visuals. See the image below. Can you check that your collisions and visuals are correct?

r2

**Comment by nkoenig** [comment]
Initial PR to resolve spawning: https://github.com/HongbiaoZ/subt_explorer_ds1_sensor_config1/pull/1

**Comment by angelacmaio** [comment]
@HongbiaoZ regarding the note in the `specifications.md`:
>* It does not model long-range Rajant wireless network of the real robot.

Does the real robot's payload include droppable communication nodes? If so, how many?

**Comment by nkoenig** [comment]
@HongbiaoZ , let me know if you need help with any of the change requests.

**Comment by HongbiaoZ** [comment]
> @HongbiaoZ regarding the note in the specifications.md:
> 
> 
> It does not model long-range Rajant wireless network of the real robot.
> 
> 
> Does the real robot's payload include droppable communication nodes? If so, how many?

Yes, it has. There are 9 nodes for each robot.

**Comment by HongbiaoZ** [comment]
> It looks like there is disagreement between the wheel collisions and visuals. See the image below. Can you check that your collisions and visuals are correct?

Yes, they are different. We use a larger radius cylinder as the collision instead of the mesh model of the tire to simplify the model.  But that will not influence the performance of the robot. We can modify it if necessary.

**Comment by nkoenig** [comment]
> > It looks like there is disagreement between the wheel collisions and visuals. See the image below. Can you check that your collisions and visuals are correct?
> 
> Yes, they are different. We use a larger radius cylinder as the collision instead of the mesh model of the tire to simplify the model. But that will not influence the performance of the robot. We can modify it if necessary.

Is it safe to assume that the collision is the correct size of the wheel? I'm asking because I'm working on integration of [these meshes](https://app.ignitionrobotics.org/OpenRobotics/fuel/models/EXPLORER_R2_VISUALS_ONLY), and I want to make sure the scale is correct.

**Comment by HongbiaoZ** [comment]
> It looks like there is disagreement between the wheel collisions and visuals. See the image below. Can you check that your collisions and visuals are correct?
> 
> Yes, they are different. We use a larger radius cylinder as the collision instead of the mesh model of the tire to simplify the model. But that will not influence the performance of the robot. We can modify it if necessary.
> 
> Is it safe to assume that the collision is the correct size of the wheel? I'm asking because I'm working on integration of these meshes, and I want to make sure the scale is correct.

Yes, it is safe. You can use these meshes with no worries.

**Comment by acschang** [comment]
The initial assessment of the Explorer R2 model is complete, however there are some issues to resolve before this model can be merged and utilized in a competitive setting:

- The mass listed in `specifications.md` does not match the mass in `model.sdf`.  Please ensure both files reflect the physical robot's mass.
- The model does not turn when yaw commands are applied on the `cmd_vel` topic. Please check and correct the vehicle's ability to achieve the commanded yaw velocity. We will work to help resolve the `diff_drive` implementation.
- Any limits on the physical robot's rotational suspension (maximum angles or non-zero spring coefficients) should be reflected in the `Center Pivot` joint in `model.sdf` and noted in `specifications.md`.
- The second IMU listed in the `specifications.md` file is not present in the model. Please rectify this issue by adding the additional IMU sensor at the proper location in the model.
- The validation data is necessary to complete the evaluation. If not provided, the model's maximum velocity will be limited to 1m/s and battery life set to 60min. When the model validation data can be provided later, please submit a PR updating the model.

Please address the issues noted above and then submit a pull request to [this new branch](https://github.com/osrf/subt/pull/482) to update your submission by 15 JULY. The submissions are expected to be incorporated into the SubT Virtual Testbed pending a successful review.

**Comment by nkoenig** [comment]
This PR has been superseded by #482.

**Pull request closed without merging**
